import {StyleSheet} from 'react-native';
import {deviceHeight, deviceWidth} from './helper';
import {mainStyles} from './Main.css';

export const userProfileStyle = StyleSheet.create({
  userProfile: {
    width: deviceWidth,
    height: mainStyles.main.height,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'flex-start',
    alignItems: 'center',
  },
  header: {
    width: deviceWidth * 0.92,
    height: deviceHeight * 0.11,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  userInfo: {
    width: deviceWidth,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
  },
  nameAndAge: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  suggestionDetails: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: 10,
    paddingBottom: 10,
    marginBottom: 10,
  },
  suggestedUserName: {
    fontSize: 20,
    color: '#ffffff',
    fontWeight: 'bold',
    marginLeft: 10,
    marginRight: 2,
  },
  profession: {
    fontSize: 15,
    color: '#ffffff',
    marginLeft: 10,
    marginRight: 2,
  },
  displayPicture: {
    width: 200,
    height: 200,
    borderRadius: 110,
    borderWidth: 5,
    borderColor: '#ffffff',
  },
  profileButtons: {
    width: deviceWidth * 0.6,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  profileButton: {
    paddingTop: 11,
    padding: 12,
    borderRadius: 50,
    backgroundColor: '#222222',
    marginTop: 15,
  },
  premiumButton: {
    width: deviceWidth * 0.8,
    padding: 10,
    backgroundColor: '#ffffff',
    borderRadius: 50,
    borderColor: '#aaaaaa',
    borderWidth: 4,
  },
  premiumButtonText: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#111111',
    textAlign: 'center',
  },
  menu: {
    width: deviceWidth,
    display: 'flex',
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
  },
  menuOption: {
    width: deviceWidth,
    height: deviceHeight * 0.075,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  menuOptionText: {
    width: deviceWidth * 0.8,
    height: deviceHeight * 0.05,
    fontSize: 15,
    fontWeight: 'bold',
    color: '#ffffff',
    marginLeft: 10,
    padding: 5,
    borderColor: '#222222',
    borderBottomWidth: 1,
  },
});
